# Generated by Django 3.1 on 2022-01-09 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=32)),
                ('gender', models.CharField(max_length=10)),
                ('birthday', models.DateTimeField()),
                ('job', models.CharField(max_length=32)),
                ('interest', models.TextField(null=True)),
                ('skill', models.TextField(null=True)),
                ('wantingToLearn', models.TextField(null=True)),
            ],
        ),
    ]
