# Generated by Django 3.1 on 2022-01-12 05:53

from django.db import migrations, models
import json.decoder
import json.encoder


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LabelName', models.CharField(max_length=30)),
                ('InterestUser', models.JSONField(decoder=json.decoder.JSONDecoder, encoder=json.encoder.JSONEncoder)),
            ],
        ),
        migrations.CreateModel(
            name='Learn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LabelName_Learn', models.CharField(max_length=30)),
                ('wantingToLearn_User', models.JSONField(decoder=json.decoder.JSONDecoder, encoder=json.encoder.JSONEncoder)),
                ('LabelName_Skill', models.CharField(max_length=30)),
                ('Skill_User', models.JSONField(decoder=json.decoder.JSONDecoder, encoder=json.encoder.JSONEncoder)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=32)),
                ('gender', models.CharField(max_length=10)),
                ('birthday', models.DateTimeField()),
                ('job', models.CharField(max_length=32)),
                ('interest', models.TextField(null=True)),
                ('skill', models.TextField(null=True)),
                ('wantingToLearn', models.TextField(null=True)),
            ],
        ),
    ]
