# Generated by Django 3.1 on 2022-01-12 07:41

from django.db import migrations, models
import json.decoder
import json.encoder


class Migration(migrations.Migration):

    dependencies = [
        ('test_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LabelName_Skill', models.CharField(max_length=30)),
                ('Skill_User', models.JSONField(decoder=json.decoder.JSONDecoder, encoder=json.encoder.JSONEncoder, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='learn',
            name='LabelName_Skill',
        ),
        migrations.RemoveField(
            model_name='learn',
            name='Skill_User',
        ),
        migrations.AlterField(
            model_name='hobby',
            name='InterestUser',
            field=models.JSONField(decoder=json.decoder.JSONDecoder, encoder=json.encoder.JSONEncoder, null=True),
        ),
        migrations.AlterField(
            model_name='learn',
            name='wantingToLearn_User',
            field=models.JSONField(decoder=json.decoder.JSONDecoder, encoder=json.encoder.JSONEncoder, null=True),
        ),
    ]
