# Generated by Django 3.1 on 2022-01-12 08:10

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('test_api', '0003_auto_20220112_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hobby',
            name='InterestUser',
            field=jsonfield.fields.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='learn',
            name='wantingToLearn_User',
            field=jsonfield.fields.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='skill',
            name='Skill_User',
            field=jsonfield.fields.JSONField(default=list),
        ),
    ]
