# Generated by Django 3.1 on 2022-01-12 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_api', '0002_auto_20220112_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hobby',
            name='InterestUser',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='learn',
            name='wantingToLearn_User',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='Skill_User',
            field=models.TextField(null=True),
        ),
    ]
